Repository vkamiansky/analysis-practice-jul-2019, pull requests merged in 2019-07, with the labels that each got.

#1 Parser is ready
  .gitignore
  Models/Answer.cs
  Models/Person.cs
  Models/PersonTestResult.cs
  Models/Question.cs
  Parser.cs
  Program.cs
  QuizResults.csproj
  appsettings.json
Labels: enhancement

#5 Fixed codepage issue and introduced skipping irrelevant letters.
  .gitignore
  Parser.cs
  QuizResults.csproj
Labels: bug

#7 Enhancement/data analysis
  DataAnalyzer.cs
  DataAnalyzerReport.cs
  Program.cs
  QuestionStatistics.cs
  QuizResults.sln
Labels: enhancement

#10 Unit tests for parser and restructuring of the project
  .gitignore
  QuizResults.sln
  appsettings.json
  src/QuizData.Analyser/DataAnalyzer.cs
  src/QuizData.Analyser/Models/DataAnalyzerReport.cs
  src/QuizData.Analyser/Models/QuestionStatistics.cs
  src/QuizData.Analyser/QuizData.Analyser.csproj
  src/QuizData.Parser/Models/Answer.cs
  src/QuizData.Parser/Models/Person.cs
  src/QuizData.Parser/Models/PersonTestResult.cs
  src/QuizData.Parser/Models/Question.cs
  src/QuizData.Parser/Parser.cs
  src/QuizData.Parser/QuizData.Parser.csproj
  src/QuizData/Program.cs
  src/QuizData/QuizData.csproj
  src/QuizData/appsettings.json
  test/QuizData.Parser.Test/CsvParserTests.cs
  test/QuizData.Parser.Test/QuizData.Parser.Test.csproj
Labels: enhancement

#12 From collection to sequence in Parser
  src/QuizData.Parser/Parser.cs
  test/QuizData.Parser.Test/CsvParserTests.cs
Labels: enhancement

#13 Enhancement/data analysis
  QuizResults.sln
  src/QuizData.Analyser/DataAnalyzer.cs
  src/QuizData.Analyser/Models/QuestionStatistics.cs
  src/QuizData.Parser/IParser.cs
  src/QuizData.Parser/Parser.cs
  src/QuizData/Program.cs
  src/QuizData/QuizData.csproj
  test/QuizData.Analyser.Test/DataAnalyserTests.cs
  test/QuizData.Analyser.Test/QuizData.Analyser.Test.csproj
Labels: enhancement

#14 Fix/encoding
  src/QuizData.Parser/EncodingDetector.cs
  src/QuizData.Parser/IParser.cs
  src/QuizData.Parser/Parser.cs
  src/QuizData/Program.cs
  test/QuizData.Parser.Test/Common.cs
  test/QuizData.Parser.Test/CsvParserTests.cs
  test/QuizData.Parser.Test/EncodingDetectorTests.cs
Labels: bug, enhancement

#18 Analyser is ready for incremental data input
  src/QuizData.Analyser/DataAnalyzer.cs
  src/QuizData.Analyser/Models/DataAnalyzerReport.cs
  src/QuizData.Analyser/Models/QuestionStatistics.cs
  test/QuizData.Analyser.Test/DataAnalyserTests.cs
Labels: enhancement

#22 Added linear approximation and unit tests for it
  QuizResults.sln
  src/QuizData.LinearApproximation/LinearApproximation.cs
  src/QuizData.LinearApproximation/QuizData.LinearApproximation.csproj
  test/QuizData.LinearApproximation.Test/LinearApproximationTests.cs
  test/QuizData.LinearApproximation.Test/QuizData.LinearApproximation.Test.csproj
Labels: enhancement

#17 Added text output to file
  QuizResults.sln
  src/QuizData.TextReport/QuizData.TextReport.csproj
  src/QuizData.TextReport/TextReporter.cs
  src/QuizData/Program.cs
  src/QuizData/QuizData.csproj
  test/QuizData.Report.Test/QuizData.Report.Test.csproj
  test/QuizData.Report.Test/TextReporterTests.cs
Labels: enhancement
